### ISSUE TITLE
CHUDP binds to all interfaces

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/klh10#19]
The Chaosnet UDP tunnel listens to all interfaces, including the tun interface used by the IMP.

I used a firewall rule to forward all Chaosnet UDP packets from the host to the ITS IP number.  Then @b4 asked if this was necessary, and that got me thinking that it shouldn't be.  But it was, and it worked.  When I removed the rule, it still worked.

So I looked in the code, and there it was: dpchudp.c binds to INADDR_ANY.

Maybe chudp should accept a parameter, say `if`, and bind only to those interfaces.

**Comment by bictorv** [comment]
If you want to restrict chudp, you could use firewall rules?

**Comment by larsbrinkhoff** [comment]
I don't remember what I issue I thought this might cause.  I suppose it's not very important, so I'll close.
