### ISSUE TITLE
Warning in build for bld-ks-its

### ISSUE THREAD

**Issue by DavidGriffith** [PDP-10/klh10#45]
Towards the end of building the `bld-ks-its` target, I get this warning:

````
../../src/dpimp.c: In function âarp_reqâ:
../../src/dpimp.c:1210:2: warning: âmemcpyâ reading 6 bytes from a region of size 4 [-Wstringop-overflow=]
  memcpy((char *)arp.arp.arp_spa,  /* Sender IP addr */
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   (char *)&ihost_ip, sizeof(arp.arp.arp_sha));
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc  -o dpimp dpimp.o dpsup.o  
````

**Comment by Rhialto** [comment]
Indeed! That warning seems to be right. The memcpy is copying into the field `arp.arp.arp_spa` but using the size of `arp.arp.arp_sha`. I would say that it needs to use the same size, right?

**Comment by Rhialto** [comment]
I made that cheange, can you check it gets rid of the warning for you?

I also started to make more changes to remove warnings from `-Wall` but I was shocked at how many they are. I did just a few.

**Comment by DavidGriffith** [comment]
That does the trick.  Thanks!
