### ISSUE TITLE
Confused installing kl, ks, and ks-its simultanously

### ISSUE THREAD

**Issue by DavidGriffith** [PDP-10/klh10#46]
The instructions and Makefile seem fuzzy on the notion of having all three emulators: `kl`, `ks`, and `ks-its` installed at the same time.  In `doc/install.txt`, I read that I should do `make -C bld-<model> install`.  But for each successive run of that for a different model, the previous install gets thrown into `$KLH10_HOME/flushed`.  The instructions aren't clear how that directory is used.  It seems that it be easier if we could install the assorted binaries to `$KLH10_HOME/<model>/`.

Am I missing something really obvious here?

**Comment by larsbrinkhoff** [comment]
My random thought is that it looks like installing multiple emulators under a single KLH10_HOME isn't supported.  Or maybe it was in a previous version, and bitrot set in.

**Comment by Rhialto** [comment]
I have to admit that I hardly ever "install" the emulators.

And indeed, there is lots of bitrot in things like building instructions. Patches welcome.

**Comment by DavidGriffith** [comment]
What is the purpose of `$KLH10_HOME/flushed`?

**Comment by larsbrinkhoff** [comment]
I would guess it's to backup the previous installation.
