### ISSUE TITLE
Merge Rich Alderson's changes

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/klh10#7]
http://www.panix.com/~alderson/klh10-2.0h_for_OSX.6.8/

**Comment by Rhialto** [comment]
Now we can see what he actually changed.

**Comment by larsbrinkhoff** [comment]
There aren't many changes.  I should create a pull request.

**Comment by Rhialto** [comment]
I think most are even covered by changes we had already. Off the top of my head, I remember a few different things:
- the "gcc code generation fix" as seen from multiple sources (already included)
- remove some remaining, unneeded, dependencies on pc console lights and its object file dvlites.o via KLH10_DEV_LITES (done somewhat differently but also effective)
- the symbolic names for the shared memory call (that I applied recently)
- maybe a bit more I'm forgetting right now.
