### ISSUE TITLE
Dies creating the first RP06 device (hopefully someone actually monitors this ;) )

### ISSUE THREAD

**Issue by gryphon-3rd** [PDP-10/klh10#71]
The PDP-10 (specifically the KA-10) was the first computer I ever used and my first job was as a TOPS-20 assembly language programmer, so I wanted to play around.  I am on a UBUNTU linux system.  After some bumbling around I got it built and it 'starts' ok
Compiled for unknown-linux-gnu on x86_64 with word model USEINT
Emulated config:
         CPU: KL10-extend   SYS: T20   Pager: KL  APRID: 3600
         Memory: 8192 pages of 512 words  (SHARED)
         Time interval: INTRP   Base: OSGET
         Interval default: 60Hz
         Internal clock: OSINT
         Other: MCA25 CIRC JPC DEBUG PCCACHE CTYINT EVHINT
         Devices: DTE RH20 RPXX(DP) TM03(DP) NI20(DP)
[MEM: Allocating 8192 pages shared memory, clearing...done]

KLH10# ; Sample KLH10.INI for initial installation
KLH10#
KLH10# ; Define basic device config - one DTE, one disk, one tape.
KLH10# ; Use two RH20s because TOPS-10 doesn't like mixing disk and tape on
KLH10# ; the same controller (TOPS-20 is fine).
KLH10#
KLH10# devdef dte0 200   dte    master
KLH10# devdef rh0  540   rh20
KLH10# ;devdef rh1  544   rh20
KLH10# devdef dsk0 rh0.0 rp     type=rp06 format=dbd9
KLH10# ;devdef mta0 rh1.0 tm03  type=tu45
KLH10#
KLH10# ; Need KLNI to avoid LAPRBF BUGCHKs - use valid address if known
KLH10# ;
KLH10# ; devdef ni0 564 ni20 ipaddr=10.0.0.51
KLH10# ; The (NetBSD/FreeBSD/Linux) version with tap(4) and bridge(4) creates the
KLH10# ; named tap device dynamically and bridges it to the default interface.
KLH10# ; If you want it differently (for instance routed instead of bridged),
KLH10# ; you can create the tap yourself and it will be used as it is.
KLH10# ;devdef ni0 564 ni20 ipaddr=10.0.0.51 ifmeth=tap+bridge ifc=tap0 dedic=true
KLH10# ; Use ifmeth=tap if you handle the bridging or routing yourself.
KLH10#
KLH10# ; Use this version if you want to use libpcap for ethernet access.
KLH10# ;devdef ni0 564 ni20 ipaddr=10.0.0.51 ifmeth=pcap ifc=re0 dedic=false
KLH10#
KLH10# ; Load disk bootstrap directly
KLH10# load boot.sav
Using word format "c36"...
Loaded "boot.sav":
Format: DEC-CSAV
Data: 4630, Symwds: 0, Low: 040000, High: 054641, Startaddress: 040000
Entvec: JRST (120 ST: 0, 124 RE: 0, 137 VR: 0,,0)
KLH10#
KLH10# ; Now ready to GO
KLH10# [EOF on klt20.ini]
KLH10# [Creating RP06 disk file "RH20.RP06.1"]

It just stops here with a zero length file created.  Does anyone know what I am doing wrong?  When I try the inst-klt20.ini file, it can't find the .tap file.   Any help would be appreciated.
John

**Comment by gryphon-3rd** [comment]
I figured it out after another hour or two of searches... It's up and running now!

**Comment by gryphon-3rd** [comment]
done

**Comment by brouhaha** [comment]
> I figured it out after another hour or two of searches... It's up and
> running now!
>
What did you have to change?

>

**Comment by gryphon-3rd** [comment]
I had to download the tape image (from trailing edge) and use that to populate the rp06. There was a good sample session I was able to find and follow.  I forgot how complicated old systems were to install. On Jan 27, 2024, at 3:11 AM, Eric Smith ***@***.***> wrote:﻿
> I figured it out after another hour or two of searches... It's up and
> running now!
>
What did you have to change?
