### ISSUE TITLE
Make supdup compile

### ISSUE THREAD

**Issue by Rhialto** [PDP-10/klh10#8]
contrib/supdup doesn't compile on modern Unix. I've started to modernize it so that it compiles, but it is not finished yet. Hopefully it is going to work with ITS after that.

**Comment by larsbrinkhoff** [comment]
I know some people have their personal, updated version of this supdup.  I'd like to bring them all together.  Maybe in a separate repository?

**Comment by Rhialto** [comment]
Good plan. Saves me some work :-)

**Comment by Rhialto** [comment]
Good plan. Saves me some work :-)

**Comment by larsbrinkhoff** [comment]
Thanks, please remind me occasionally.
